  services:

    tigerbeetle_data:
      image: ghcr.io/tigerbeetle/tigerbeetle
      command: "format --cluster=0 --replica=0 --replica-count=1 /data/0_0.tigerbeetle"
      volumes:
        - './volumes/tigerbeetle/data:/data'
      networks:
        - app-network

    tigerbeetle:
      image: ghcr.io/tigerbeetle/tigerbeetle
      depends_on:
        - tigerbeetle_data
      command: "start --addresses=0.0.0.0:3000 /data/0_0.tigerbeetle"
      ports:
        - 3002:3000
      volumes:
        - './volumes/tigerbeetle/data:/data'
      security_opt:
        - "seccomp=unconfined"
      networks:
        - app-network

  networks:
    app-network:
      driver: bridge