spring:
  application:
    name: tiger-madness
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  shell:
    interactive:
      enabled: true

dcrdemo:
  tigerbeetle:
    replica:
      cluster-id: 0
      addresses: 3000
